### ISSUE TITLE
missing term in equation?

### ISSUE THREAD

**Issue by notwa** [linebender/spline#12]
I was snooping through the code and I found something peculiar.
https://github.com/linebender/spline/blob/e4718e9e590f99cb0edf0c2c342af91a020622c9/src/hyperbezier.rs#L261-L263
it may be that it doesn't matter in the context of *compute\_theta,* but when bias ≥ 1.0002, *integrate\_basis* has a huge y-offset for smaller values of *bias.* for instance, `integrate_basis(1.0002, 0.0) = 49986667.306`. I believe the numerator is missing a -1 term, like so:
```rust
    (1.0 / (1.0 - a * s) + (1.0 - a * s).ln() - 1.0) / norm
```

**Comment by raphlinus** [comment]
Good catch! From a mathematical point of view, it doesn't matter because only the definite integral is computed (any integration constant is subtracted out). But because these values can get large, it reduces precision, so adding your term would be an improvement.

I'll happily take a PR, or fold this into another commit as I continue work.

**Comment by notwa** [comment]
nah, you should just commit this yourself.
